export const resume = {
  name: "Jeff Keith",
  headline: "Senior Full Stack Engineer / Engineering Manager",
  location: "North Port, FL",
  email: "me@jeffkeith.me",
  phone: "585 738 8598",
  summary:
    "Senior Full Stack Engineer and Engineering Manager with 20+ years of experience designing, building, and scaling production web applications while leading high-performing teams. Strong background in TypeScript/JavaScript stacks, system architecture, cloud platforms, and end-to-end feature ownership. Builder-minded technical leader who combines hands-on engineering with people leadership, architectural direction, mentoring, and cross-functional collaboration. Experienced owning complex systems from design through production while also supporting team growth and delivery excellence. Recently completed a focused professional development period deepening expertise in AI-enabled systems, modern application architecture, and production-grade integrations. Passionate about building reliable, elegant software, raising engineering standards, and leveraging AI to accelerate product development and team effectiveness.",
  professionalDevelopment: {
    title: "Professional Development – AI & Full Stack Technical Leadership",
    subtitle: "Independent Study / Hands-On Projects",
    range: "May 2025 – Present",
    bullets: [
      "Intentional professional development period focused on strengthening principal-level engineering skills across full-stack architecture, AI integration, and production system design. Built two prototype applications: sloot.ai, an agentic automation platform with connectivity to 2,500+ services and custom MCP servers; and genny.bot, a generative AI application for creating and manipulating images and video using modern multimodal models. GitHub repositories, architectural deep-dives, and live application walkthroughs are available upon request.",
      "Built and deployed MCP (Model Context Protocol) servers, enabling structured, secure interaction between applications and AI models.",
      "Designed and implemented web-based applications integrated with AI/ML models, including OpenAI, Claude, Gemini, Grok, and DeepSeek.",
      "Gained hands-on experience orchestrating multi-model workflows, prompt design, tool calling, and system boundaries.",
      "Explored best practices for AI integration in production systems, including reliability, observability, and responsible usage.",
      "Applied learnings to accelerate feature development, improve developer workflows, and prototype complex systems quickly.",
      "Used this period to sharpen architectural judgment and return to the workforce as a hands-on technical leader capable of owning complex systems while guiding teams through modern AI-driven development.",
    ],
  },
  experience: [
    {
      role: "Engineering Manager",
      company: "ButcherBox",
      location: "Boston, MA",
      range: "July 2021 – May 1, 2025",
      bullets: [
        "Led and supported a cross-functional engineering team through all Scrum ceremonies, fostering accountability, engagement, and continuous improvement.",
        "Conducted weekly 1:1s focused on career growth, performance feedback, and team health.",
        "Reviewed code regularly to ensure quality, knowledge sharing, and removal of technical blockers.",
        "Interviewed, hired, and onboarded engineers, contributing to team growth and culture.",
        "Partnered closely with Product Management and Scrum leadership to align delivery with OKRs and business goals.",
        "Implemented an improved release flow that reduced production defects and improved overall customer experience.",
        "Notable features released include a new member recipe experience, an AI-enhanced cancellation flow leveraging Palantir Foundry, and a trial box membership offering.",
      ],
    },
    {
      role: "Lead Developer",
      company: "Records One",
      location: "Rochester, NY",
      range: "March 2019 – July 2021",
      bullets: [
        "Managed a fully remote development team in a Scrum environment.",
        "Led sprint ceremonies including daily standups, refinement, retrospectives, and reviews.",
        "Reviewed, approved, and merged pull requests while mentoring engineers on best practices.",
        "Coordinated JavaScript releases and deployments with server and data teams.",
        "Designed and developed Node.js APIs and integrated them into front-end applications.",
        "Built CI pipelines and integration tests using Jenkins.",
        "Improved build and deployment workflows through custom Grunt tasks.",
      ],
    },
    {
      role: "Web Application Developer",
      company: "FabSuite / Trimble",
      location: "Kennesaw, GA",
      range: "January 2016 – April 2019",
      bullets: [
        "Primary developer for FabSuite Go, an API-driven platform for steel fabrication project management.",
        "Designed and implemented features for inventory, shipping, inspections, and 3D model integration.",
        "Developed custom routing frameworks and implemented Google Material Design standards.",
        "Worked remotely in a Scrum-based environment using Jira and Google Workspace.",
      ],
    },
    {
      role: "Web Application Developer (freelance)",
      company: "Gigaweb / SavingLots.com / AsSeenOnTv.com",
      location: "Rochester, NY",
      range: "1997 – 2016",
      bullets: [
        "Designed, built, and maintained custom web applications and e-commerce platforms across freelance, startup, and owner-operator roles.",
        "Delivered custom websites and marketing solutions for small businesses, improving visibility, conversions, and operational efficiency.",
        "Founded and operated an e-commerce platform, implementing payment processing, real-time inventory, shipping integrations, and administrative tooling.",
        "Developed full e-commerce systems using PHP and MySQL, contributing to early growth and long-term scalability.",
      ],
    },
  ],
  education: [
    {
      title: "Computer Science (No Degree)",
      school: "Rochester Institute of Technology",
      location: "Rochester, NY",
      range: "1996 – 1998",
    },
    {
      title: "Associate’s Degree – Business Management",
      school: "Finger Lakes Community College",
      location: "",
      range: "1990 – 1994",
    },
  ],
  technicalSkills: [
    {
      group: "Core Languages",
      skills: ["JavaScript (ES6+)", "TypeScript", "SQL", "HTML", "CSS"],
    },
    { group: "Modern Frameworks", skills: ["React", "Remix", "Node.js"] },
    {
      group: "AI / LLM Integration",
      skills: [
        "OpenAI",
        "Claude",
        "Gemini",
        "Grok",
        "DeepSeek",
        "MCP Servers",
        "Prompt Engineering",
        "Tool Calling",
      ],
    },
    { group: "Platforms & Cloud", skills: ["AWS", "Docker", "Linux/Ubuntu"] },
    { group: "Datastores", skills: ["PostgreSQL", "MySQL", "MongoDB"] },
    { group: "DevOps & Delivery", skills: ["Git", "CI/CD", "Jenkins"] },
    { group: "Product & Commerce", skills: ["Shopify", "WordPress"] },
    {
      group: "Ways of Working",
      skills: ["Agile", "Scrum", "System Design", "Engineering Management"],
    },
  ],
};
