export const resume = {
  name: "Jeff Keith",
  headline: "Senior Full Stack Engineer / Engineering Manager",
  location: "North Port, FL",
  email: "me@jeffkeith.me",
  phone: "585 738 8598",
  summary:
    "Senior Full Stack Engineer and Engineering Manager with 20+ years of experience designing, building, and scaling production software across e-commerce, SaaS, AI, healthcare, and enterprise platforms. Deep expertise in TypeScript, React, Node.js, cloud architecture, distributed systems, and AI-enabled applications. Proven track record leading engineering teams, architecting complex systems, and delivering customer-facing products serving millions of users. Currently serving as Founding AI Engineer at genny.bot, building multimodal AI products leveraging agentic workflows, MCP servers, voice AI, and modern generative AI platforms.",
  experience: [
    {
      role: "Founding AI Engineer",
      company: "genny.bot",
      location: "",
      range: "May 2025 – Present",
      bullets: [
        "Founded and built an AI-native application platform focused on multimodal content creation, voice experiences, agentic workflows, and AI-powered automation.",
        "Architected and launched a multimodal AI platform integrating OpenAI, Anthropic Claude, Gemini, Grok, DeepSeek, ElevenLabs, Veo, Kling, Seedance, and other generative AI providers.",
        "Designed agentic workflows, MCP servers, tool-calling architectures, and multi-model orchestration pipelines.",
        "Developed scalable React and TypeScript applications supporting streaming AI conversations, media generation, voice cloning, character creation, avatar experiences, and workflow automation.",
        "Built production-grade AI infrastructure including observability, prompt evaluation, structured outputs, monitoring, reliability testing, and cost optimization.",
        "Leveraged AI-native development workflows using Cursor, Claude, ChatGPT, and custom automation tooling to accelerate product development and experimentation.",
        "React, Typescript, Node.js, Express.js, Docker, Vercel, AI Gateway, Composio,AWS, Supabase, Postgres, Stripe, Cursor, Claude Code",
      ],
    },
    {
      role: "Engineering Manager",
      company: "ButcherBox",
      location: "",
      range: "July 2021 – May 2025",
      bullets: [
        "Led a cross-functional engineering team responsible for customer lifecycle experiences, subscription management, retention initiatives, and experimentation platforms serving millions of subscribers.",
        "Partnered with Product, Analytics, Design, and Executive stakeholders to define technical strategy, roadmap priorities, and delivery execution.",
        "Delivered an AI-assisted retention platform leveraging Palantir Foundry, behavioral data, experimentation frameworks, and personalized customer experiences.",
        "Implemented release and deployment improvements that reduced production defects and increased delivery confidence.",
        "Mentored engineers through architecture reviews, code reviews, career development, and technical leadership.",
        "React, Remix, Typescript, PHP Laravel, Shopify Hydrogen, Liquid, Node.js,Docker, Azure, SQL, GraphQL, Contentful, Shopify Plus, Checkout Extensibility, Shopify Functions and APIs, React Query, Klaviyo, Segment, Claude Code, Cursor, Jira, Confluence, Agile, Github actions, CI/CD, Stripe, Optimizely, Datadog, Cypress",
      ],
    },
    {
      role: "Lead Full Stack Engineer",
      company: "Records One",
      location: "",
      range: "March 2019 – July 2021",
      bullets: [
        "Architected and developed healthcare software solutions supporting enterprise clinical data workflows.",
        "Led development of Node.js APIs, frontend applications, CI/CD pipelines, testing frameworks, and deployment processes.",
        "Managed a remote engineering team and guided technical design and delivery.",
        "React, Typescript, Node.js, Docker, Postgres, Git, CI/CD, Jenkins, Agile, Scrum",
      ],
    },
    {
      role: "Senior Full Stack Engineer",
      company: "FabSuite / Trimble",
      location: "",
      range: "January 2016 – April 2019",
      bullets: [
        "Primary developer for FabSuite Go, an API-driven steel fabrication management platform.",
        "Designed and implemented inventory, shipping, inspection, and 3D model integration capabilities.",
        "React, Typescript, Node.js, Docker, Postgres, Git, CI/CD, Jenkins, Agile, Scrum",
      ],
    },
    {
      role: "Full Stack Engineer",
      company: "Freelance / AsSeenOnTv.com / SavingLots.com",
      location: "",
      range: "1997 – 2016",
      bullets: [
        "Built custom web applications, e-commerce platforms, payment integrations, membership systems, and business applications.",
        "Founded and operated SavingLots.com, developing custom commerce, inventory, payment, and fulfillment systems.",
        "Wordpress, Shopify, PHP, Javascript, HTML, CSS",
      ],
    },
  ],
  education: [
    {
      title: "Computer Science",
      school: "Rochester Institute of Technology",
      location: "",
      range: "1996 – 2000",
    },
    {
      title: "Business Management",
      school: "Finger Lakes Community College",
      location: "",
      range: "1990 – 1992",
    },
  ],
  technicalSkills: [
    {
      group: "Languages",
      skills: ["TypeScript", "JavaScript (ES6+)", "SQL", "PHP", "HTML", "CSS"],
    },
    {
      group: "Frontend",
      skills: ["React", "React Native", "Next.js", "Remix"],
    },
    {
      group: "Backend & APIs",
      skills: [
        "Node.js",
        "Express",
        "GraphQL",
        "REST APIs",
        "Laravel",
        "Shopify Hydrogen",
        "Shopify Functions and APIs",
        "Shopify Plus",
      ],
    },
    {
      group: "AI Engineering",
      skills: [
        "Cursor",
        "Claude Code",
        "OpenAI",
        "Claude",
        "Gemini",
        "Grok",
        "DeepSeek",
        "ElevenLabs",
        "Generative AI Models",
        "LangChain",
        "MCP Servers",
        "Agentic Workflows",
        "Prompt Engineering",
        "Tool Calling",
        "Multimodal AI",
      ],
    },
    {
      group: "Cloud & Infrastructure",
      skills: ["AWS", "GCP", "Docker", "Linux/Ubuntu", "CI/CD", "Azure", "Docker", "Vercel"],
    },
    {
      group: "Data & Storage",
      skills: ["PostgreSQL", "MySQL", "MongoDB"],
    },
    {
      group: "Observability & Testing",
      skills: ["Datadog", "Sentry", "Cypress"],
    },
    {
      group: "Commerce & Product",
      skills: ["Shopify", "Stripe", "WordPress", "Optimizely", "Contentful", "Segment"],
    },
    {
      group: "Leadership & Delivery",
      skills: ["System Design", "Agile", "Scrum", "Engineering Management", "Technical Leadership"],
    },
  ],
};
